### ISSUE TITLE
Release TODO's

### ISSUE THREAD

**Issue by jessemorris** [ACFR-RPG/DynOSAM#21]
List of TODO's before release. Mostly minor and user/examples

- [ ] DataLoader examples taking input from CMD line and displaying images (and gt to ROS if available?)
- [x] Remove all unncessary files (ego the gross DynoISAM2 stuff)
- [ ] Refactor evaluation into proper evo style files (particulary the functions we've copied and modified)
- [ ] Run parallel mode
- [ ] https://github.com/marketplace/actions/doxygen-github-pages-deploy-action
